In [2]:
import numpy as np

In [14]:
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [5]:
type(arr1)

numpy.ndarray

In [6]:
# 1D Array of len == 9
arr1.shape

(9,)

In [7]:
arr1[4]

48

In [8]:
arr1[1:4]

array([21, 32, 43])

In [9]:
indices = [1, 2, 5, 6]
arr1[indices]

array([21, 32, 15, 76])

In [11]:
mask = (arr1 % 2 == 0) # valores pares
print(mask)
arr1[mask]

[ True False  True False  True False  True False False]


array([10, 32, 48, 76])

In [13]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)

[1 2 3 4 5]


In [16]:
arr2.cumsum() # Soma acumulada 

array([ 1,  3,  6, 10, 15])

In [17]:
arr2.cumprod() # Multiplicação acumulada

array([  1,   2,   6,  24, 120])

In [19]:
arr3 = np.arange(0, 50, 5)
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]
